title: SG Documentation
description: Testing
theme: just-the-docs

url: woolbeach-sg.github.io/documentation/

# Logo settings
logo: "/Assets/SG-logo_plain.png"

aux_links: # remove if you don't want this link to appear on your pages
  Github Repository: woolbeach-sg.github.io

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Adgangsstyring"
    url: /adgangsstyring/
  - title: "ID-Portal"
    url: /id-portal/
plugins:
  - jekyll-last-modified-at
  - jekyll-git-metadata