title: SG Documentation
description: Testing
theme: just-the-docs

url: woolbeach-sg.github.io/documentation/

logo: "/Assets/SG-logo_plain.png"

aux_links: # remove if you don't want this link to appear on your pages
  Github Repository: woolbeach-sg.github.io

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Adgangsstyring"
    url: /adgangsstyring/
    children:
      - title: "Roller og rettigheder"
        url: /adgangsstyring/roller_og_rettigheder/
      - title: "Identifikationsmidler"
        url: /adgangsstyring/identifikationsmidler/
      - title: "FK Administration"
        url: /adgangsstyring/fk_administration/
      - title: "FK Organisation"
        url: /adgangsstyring/fk_organisation/
      - title: "ADFS Log"
        url: /adgangsstyring/adfs_log/
      - title: "Certifikatstyring"
        url: /adgangsstyring/identifikationsmidler/  
      - title: "FBRS Rettigheder"
        url: /adgangsstyring/fbrs/
      - title: "Indstillinger"
        url: /adgangsstyring/indstillinger/ 
      - title: "Tekniske konfigurationsdetaljer"
        url: /adgangsstyring/tekniske_konfigurationsdetaljer/  

# Collection settings
collections:
  docs:
    output: true
    permalink: /docs/:path/