title: SG Documentation
description: Testing
theme: just-the-docs

url: woolbeach-sg.github.io/documentation/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: woolbeach-sg.github.io

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Adgangsstyring"
    url: /adgangsstyring/
    children:
      - title: "[2] Roller og rettigheder"
        url: /adgangsstyring/roller_og_rettigheder/
      - title: "[3] Identifikationsmidler"
        url: /adgangsstyring/identifikationsmidler/
      - title: "[4] FK Administration"
        url: /adgangsstyring/fk_administration/
      - title: "[5] FK Organisation"
        url: /adgangsstyring/fk_organisation/
      - title: "[6] ADFS Log"
        url: /adgangsstyring/adfs_log/
      - title: "[7] Certifikatstyring"
        url: /adgangsstyring/identifikationsmidler/  
      - title: "[8] FBRS Rettigheder"
        url: /adgangsstyring/fbrs/
      - title: "[9] Indstillinger"
        url: /adgangsstyring/indstillinger/ 
      - title: "[10] Tekniske konfigurationsdetaljer"
        url: /adgangsstyring/tekniske_konfigurationsdetaljer/  

# Collection settings
collections:
  docs:
    output: true
    permalink: /docs/:path/