title: SG Documentation
description: Testing
theme: just-the-docs

url: woolbeach-sg.github.io/documentation/

# Logo settings
logo: "/Assets/SG-logo_plain.png"

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Adgangsstyring"
    url: /adgangsstyring/
  - title: "ID-Portal"
    url: /id-portal/
plugins:
  - jekyll-last-modified-at